/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InfoGraphic {
        "boxColor": string;
        "centerColor": string;
        "centerImg": string;
        "centerText": string;
        "content": string;
        "iconAcitveColor": string;
        "iconBodyFive": string;
        "iconBodyFour": string;
        "iconBodyOne": string;
        "iconBodyThree": string;
        "iconBodyTwo": string;
        "iconHeaderFive": string;
        "iconHeaderFour": string;
        "iconHeaderOne": string;
        "iconHeaderThree": string;
        "iconHeaderTwo": string;
        "iconImgFive": string;
        "iconImgFour": string;
        "iconImgOne": string;
        "iconImgThree": string;
        "iconImgTwo": string;
        "iconTitleFive": string;
        "iconTitleFour": string;
        "iconTitleOne": string;
        "iconTitleThree": string;
        "iconTitleTwo": string;
        "iconsNumber": number;
    }
}
declare global {
    interface HTMLInfoGraphicElement extends Components.InfoGraphic, HTMLStencilElement {
    }
    var HTMLInfoGraphicElement: {
        prototype: HTMLInfoGraphicElement;
        new (): HTMLInfoGraphicElement;
    };
    interface HTMLElementTagNameMap {
        "info-graphic": HTMLInfoGraphicElement;
    }
}
declare namespace LocalJSX {
    interface InfoGraphic {
        "boxColor"?: string;
        "centerColor"?: string;
        "centerImg"?: string;
        "centerText"?: string;
        "content"?: string;
        "iconAcitveColor"?: string;
        "iconBodyFive"?: string;
        "iconBodyFour"?: string;
        "iconBodyOne"?: string;
        "iconBodyThree"?: string;
        "iconBodyTwo"?: string;
        "iconHeaderFive"?: string;
        "iconHeaderFour"?: string;
        "iconHeaderOne"?: string;
        "iconHeaderThree"?: string;
        "iconHeaderTwo"?: string;
        "iconImgFive"?: string;
        "iconImgFour"?: string;
        "iconImgOne"?: string;
        "iconImgThree"?: string;
        "iconImgTwo"?: string;
        "iconTitleFive"?: string;
        "iconTitleFour"?: string;
        "iconTitleOne"?: string;
        "iconTitleThree"?: string;
        "iconTitleTwo"?: string;
        "iconsNumber"?: number;
        "onUpdateSatisfiedEvent"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "info-graphic": InfoGraphic;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "info-graphic": LocalJSX.InfoGraphic & JSXBase.HTMLAttributes<HTMLInfoGraphicElement>;
        }
    }
}
